### ISSUE TITLE
Npm Start failing with BAD DECRYPT error

### ISSUE THREAD

**Issue by JongsmaSimon** [stas-demydiuk/ewpe-smart-mqtt#4]
I am running ewpe-smart-mqtt on Raspbian Stretch 4.19.66. I am using node v12.10.0 all other OS components were upgraded. On npm start i get (after detecting my Hunter/Cooper airco's) a decryption error:
npm start

> ewpe-smart-mqtt@1.0.0 start /home/pi/nodejs/ewpe-smart-mqtt
> node index.js

2019-10-06T21:45:36.232Z [info]: "Server is listening on 0.0.0.0:47709"
2019-10-06T21:45:36.270Z [info]: "New device found: 1e775dd7 (f4911e775dd7), binding..."
2019-10-06T21:45:36.292Z [info]: "New device bound: 1e775dd7 (192.168.178.48:7000)"
2019-10-06T21:45:36.295Z [info]: "MQTT message received: ewpe-smart/f4911e775dd7 {\"cid\":\"f4911e775dd7\",\"bc\":\"000000000000000000000000000000\",\"brand\":\"gree\",\"catalog\":\"gree\",\"mac\":\"f4911e775dd7\",\"mid\":\"10001\",\"model\":\"gree\",\"name\":\"1e775dd7\",\"series\":\"gree\",\"vender\":\"1\",\"ver\":\"V1.2.1\",\"lock\":0,\"address\":\"192.168.178.48\",\"port\":7000,\"key\":\"7Ab0De3Gh6Jk9Mn2\"}"
2019-10-06T21:45:36.327Z [info]: "New device found: 1e775d28 (f4911e775d28), binding..."
2019-10-06T21:45:36.341Z [info]: "New device found: 1e775d28 (f4911e775d28), binding..."
2019-10-06T21:45:36.364Z [info]: "New device bound: 1e775d28 (192.168.178.47:7000)"
2019-10-06T21:45:36.365Z [info]: "New device bound: 1e775d28 (192.168.178.47:7000)"
2019-10-06T21:45:36.367Z [info]: "MQTT message received: ewpe-smart/f4911e775d28 {\"cid\":\"f4911e775d28\",\"bc\":\"000000000000000000000000000000\",\"brand\":\"gree\",\"catalog\":\"gree\",\"mac\":\"f4911e775d28\",\"mid\":\"10001\",\"model\":\"gree\",\"name\":\"1e775d28\",\"series\":\"gree\",\"vender\":\"1\",\"ver\":\"V1.2.1\",\"lock\":0,\"address\":\"192.168.178.47\",\"port\":7000,\"key\":\"7Ef0Hi3Kl6No9Qr2\"}"
2019-10-06T21:45:36.368Z [info]: "MQTT message received: ewpe-smart/f4911e775d28 {\"cid\":\"f4911e775d28\",\"bc\":\"000000000000000000000000000000\",\"brand\":\"gree\",\"catalog\":\"gree\",\"mac\":\"f4911e775d28\",\"mid\":\"10001\",\"model\":\"gree\",\"name\":\"1e775d28\",\"series\":\"gree\",\"vender\":\"1\",\"ver\":\"V1.2.1\",\"lock\":0,\"address\":\"192.168.178.47\",\"port\":7000,\"key\":\"7Ef0Hi3Kl6No9Qr2\"}"
internal/crypto/cipher.js:177
  const ret = this[kHandle].final();
                            ^

Error: error:06065064:digital envelope routines:EVP_DecryptFinal_ex:bad decrypt
    at Decipheriv.final (internal/crypto/cipher.js:177:29)
    at decrypt (/home/pi/nodejs/ewpe-smart-mqtt/app/encryptor.js:15:48)
    at Connection.handleResponse (/home/pi/nodejs/ewpe-smart-mqtt/app/connection.js:106:26)
    at Socket.emit (events.js:209:13)
    at UDP.onMessage [as onmessage] (dgram.js:853:8) {
  library: 'digital envelope routines',
  function: 'EVP_DecryptFinal_ex',
  reason: 'bad decrypt',
  code: 'ERR_OSSL_EVP_BAD_DECRYPT'
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! ewpe-smart-mqtt@1.0.0 start: `node index.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the ewpe-smart-mqtt@1.0.0 start script.

I also tried npm install eccrypto but that did not help.

**Comment by JongsmaSimon** [comment]
I fixed it myself. Had to do:  sudo apt install libpython3.5-dev
